### ISSUE TITLE
[1.20.1] Crash with the latest update

### ISSUE THREAD

**Issue by DankestO** [cotrin8672/CreateEnchantableMachinery#20]
Hi! With the latest update when I try to turn on my dedicated server it crashes.
With the previous version it worked for me.

[latest.log](https://github.com/user-attachments/files/16841193/latest.log)

Create: [0.5.1.f]
Kotlinforforge: [4.11.0]
Create: Enchantable Machinery: [1.1.3]

**Comment by cotrin8672** [comment]
There seems to have been a problem with the configured Workflow.
Removed the 1.1.3 version from CurseForge and Modrinth and re-uploaded the new 1.1.3 version.
Please replace the jar file and try again.

**Comment by DankestO** [comment]
Yup, it's starting to work now, thanks :D!
