### ISSUE TITLE
[1.20.1] crashes with ModernFix* as of 1.3.3

### ISSUE THREAD

**Issue by notandvm** [cotrin8672/CreateEnchantableMachinery#30]
*with dynamic_resources enabled (otherwise it loads as normal)

not sure if it's fixable, given the nature of ModernFix, but figured it'd be at least worth reporting as versions 1.2.3 and prior worked fine with no issues, and throw out a slight heads up on the off-chance it can be fixed

[latest.log](https://github.com/user-attachments/files/16923677/latest.log)
[crash-2024-09-08_16.59.11-fml.txt](https://github.com/user-attachments/files/16923678/crash-2024-09-08_16.59.11-fml.txt)

everything is the current latest version, via. forge loader - haven't tested any minecraft ver. other than 1.20.1

![image](https://github.com/user-attachments/assets/83b9bef4-9937-4cff-9446-e0d3e9788517)

**Comment by cotrin8672** [comment]
Thanks for the report!
We have probably identified the cause and will release a corrected version within the next few days.
