### ISSUE TITLE
Port to fabric?

### ISSUE THREAD

**Issue by masuteri** [cotrin8672/CreateEnchantableMachinery#39]
I haven't seen anyone else ask yet.

**Comment by cotrin8672** [comment]
Fabric support has already been discussed in the comments section of CurseForge.
We intend to launch Fabric support once we have finished implementing all planned Features. We are currently developing across three versions, 1.18.2, 1.19.2, and 1.20.1. In addition to this, if we proceed with the same development in Fabric at 1.18.2, 1.19.2, and 1.20.1, the update span will be too long.
