### ISSUE TITLE
[BUG REPORT]

### ISSUE THREAD

**Issue by Hasbetack** [cotrin8672/CreateEnchantableMachinery#51]
**Describe the bug**

**Environment**
Minecraft version : 1.20.1
mod version : 1.7.4
other mod version : [optional] 

**To Reproduce**
Craft Andesite with enchanted Mixer remove the result manually from basin -> crashes Minecraft Client and Server
(while i did it there was an inactive Blaze Burner below the basin havent tested if thats relevant but the crash msg doesnt reference it either so i doubt it)

**Expected behavior**
Not Crash (it behaves normally aside from the crash)

**Comment by cotrin8672** [comment]
Problem identified. It will be fixed in the next release.
