### ISSUE TITLE
[BUG REPORT] Server Crash with version 1.20.1-2.8.6 Fabric Loader

### ISSUE THREAD

**Issue by Knito58** [cotrin8672/CreateEnchantableMachinery#61]
**Describe the bug**
Server does not start with mod enabled.

**Environment**
Minecraft version :  1.20.1
mod version :  2.8.6
other mod version : [optional] 

**To Reproduce**
1. Have a Fabric server with loader 0.16.7
2. Copy latest version of mod into mods folder
3. Start the server
4. It crashes

**Expected behavior**
Server starts without crashing

**Pastebin**
[latest.log](https://pastebin.com/vVdVs2eX)

**Why do I blame your mod?**
Because the server said:

```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'createenchantablemachinery' at 'io.github.cotrin8672.fabric.CreateEnchantableMachineryFabric'!
    at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.7.jar:?]
bla...

```

**Comment by cotrin8672** [comment]
Thank you for your report!
I will be releasing a patch to fix this within the next few days.

**Comment by Knito58** [comment]
Server is running again with the mod installed. Thank you.
