### ISSUE TITLE
drills enchanted with silk touch do not drop blocks properly

### ISSUE THREAD

**Issue by TwistedHazel** [cotrin8672/CreateEnchantableMachinery#67]
Minecraft v1.20.1
Fabric v0.16.9 (loader 1.0.1)
Installed Mods:
- Fabric API v0.92.2
- Create Fabric v0.5.1-j-build.1631
- Create Enchantable Machinery v2.8.7
- EMI v1.1.18
- Fabric Language Kotlin v1.12.3
- Mod Menu v7.2.2

Drills enchanted with Silk Touch do not drop the original blocks when broken, instead behaving as unenchanted drills. This behavior is correct in v2.8.6, but not in v2.8.7. Only the mods listed above were installed in a creative test world, so "chunk protection" mods cannot be causing this issue.

**Comment by cotrin8672** [comment]
Thank you for your report!
I will fix it in the next version.
