### ISSUE TITLE
[Bug] Breaks Create compatibility with Open Parties & Claims

### ISSUE THREAD

**Issue by CelestialAbyss** [cotrin8672/CreateEnchantableMachinery#9]
- 1.20.1
- Forge 47.3.7
- Mod version: 1.0.2

It seems that both unenchanted and enchanted drills no longer work by default in chunks claimed with Open Parties & Claims until chunk protection is turned off by players. Normally they would work in claimed chunks if placed by the player who owns the chunk claim

I'm assuming it has to do with the fake player not being applied to the drills but I'm unsure

**Comment by cotrin8672** [comment]
What version of Minecraft are you using that is causing the problem? Is this chunk protection by FTB Chunks?

**Comment by CelestialAbyss** [comment]
Forgot to add that ;-;
This was on Forge 1.20.1, but it's likely that it also happens on 1.19.2

As for the chunk claim mod it's [Open Parties & Claims](https://www.curseforge.com/minecraft/mc-mods/open-parties-and-claims), not FTB Chunks

**Comment by cotrin8672** [comment]
This mod provides a configuration option where you can add FakePlayers to bypass chunk protection.

1. Open the config file located saves/[world-name]/serverconfig/openpartiesandclaims-server.toml
2. Edit this file as follow
```toml
#A list of fake players (UUIDs or names) that shouldn't be affected by any chunk claim protection if they try to access a chunk with building protection compatible with
#the chunk that the fake player's origin block is positioned in, e.g. claims with the same owner and block protection option values.
#This works great for fake players that are bound to the position of a specific placed block (origin block). Moreover, the mod supports fake players placed at a block
#next to the origin block, even if that means entering another chunk, e.g. in the case of the Integrated Tunnels mod, or if the origin block is touching the target block.
#The mod will try all positions next to the target block and the fake player as the possible position of the fake player origin block.
#This will always protect the target block if it or the fake player touch a claim with incompatible build protection. Avoid building on such claim edges.
#However, some fake players' origin blocks can be nowhere near the fake player or the target block, e.g. in the case of the Create mod, or there might be no origin block at all,
#e.g. NPCs that can move around. In this case, the mods that use such fake players require explicit support to be implemented. Although they might also sometimes
#be supported by default, if the fake players use UUIDs of actual players.
#Explicit support exists for the Create mod (requires an extension on Fabric) and you are not required to add anything to this list.
#Make sure to always test that claim edges are protected from outside interaction by fake players that you add to this list.
#Wondering where to get the UUIDs or usernames of specific fake players? You can check the source code of the mods that use them or politely ask the mod authors.
#For example ["41C82C87-7AfB-4024-BB57-13D2C99CAE77", "FakePlayerName"]
staticFakePlayers = ["[IntegratedTunnels]", "block_breaker", "contraption_block_breaker"]
```
3. Save the file and launch minecraft.

In the future, when reporting issues related to mod compatibility, please make sure to check the configuration options of the mods involved. Additionally, when submitting an issue, kindly include details about your environment, such as the Minecraft version, the versions of the mods you’re using, and any other relevant information. This helps in diagnosing and resolving the issue more effectively.

Thank you for your continued support of Create: Enchantable Machinery!
